language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; sudo apt-get install qtbase5-dev qt5-qmake; fi

script:
  - git submodule update --init
  - mkdir _build && cd _build
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) -DCONFIG_QT=ON -DCONFIG_TINY=ON ..; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DCONFIG_QT=ON -DCONFIG_TINY=ON .. ; fi
  - make VERBOSE=1
